// Code generated by pulumi-gen-awsconf DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package awsconf

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"internal"
)

type Configurer struct {
	pulumi.ResourceState

	AwsProvider aws.ProviderOutput `pulumi:"awsProvider"`
}

// NewConfigurer registers a new resource with the given unique name, arguments, and options.
func NewConfigurer(ctx *pulumi.Context,
	name string, args *ConfigurerArgs, opts ...pulumi.ResourceOption) (*Configurer, error) {
	if args == nil {
		args = &ConfigurerArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Configurer
	err := ctx.RegisterRemoteComponentResource("awsconf:index:Configurer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type configurerArgs struct {
	Profile *string `pulumi:"profile"`
	Region  *string `pulumi:"region"`
}

// The set of arguments for constructing a Configurer resource.
type ConfigurerArgs struct {
	Profile pulumi.StringPtrInput
	Region  pulumi.StringPtrInput
}

func (ConfigurerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*configurerArgs)(nil)).Elem()
}

type ConfigurerInput interface {
	pulumi.Input

	ToConfigurerOutput() ConfigurerOutput
	ToConfigurerOutputWithContext(ctx context.Context) ConfigurerOutput
}

func (*Configurer) ElementType() reflect.Type {
	return reflect.TypeOf((**Configurer)(nil)).Elem()
}

func (i *Configurer) ToConfigurerOutput() ConfigurerOutput {
	return i.ToConfigurerOutputWithContext(context.Background())
}

func (i *Configurer) ToConfigurerOutputWithContext(ctx context.Context) ConfigurerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConfigurerOutput)
}

type ConfigurerOutput struct{ *pulumi.OutputState }

func (ConfigurerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Configurer)(nil)).Elem()
}

func (o ConfigurerOutput) ToConfigurerOutput() ConfigurerOutput {
	return o
}

func (o ConfigurerOutput) ToConfigurerOutputWithContext(ctx context.Context) ConfigurerOutput {
	return o
}

func (o ConfigurerOutput) AwsProvider() aws.ProviderOutput {
	return o.ApplyT(func(v *Configurer) aws.ProviderOutput { return v.AwsProvider }).(aws.ProviderOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ConfigurerInput)(nil)).Elem(), &Configurer{})
	pulumi.RegisterOutputType(ConfigurerOutput{})
}
